[tool.poetry]
name = "restud"
version = "0.1.0"
description = ""
authors = ["Mikl√≥s Koren <koren@localhost>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6"
PyYAML = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
